# Generated by Django 4.0.6 on 2022-10-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0003_url_atualizado_url_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
